concurrency: 4
timeouts:
  command_seconds: 120
output:
  json: false
storage:
  enabled: true
paths:
  python: python3
  nmap: nmap
  nslookup: nslookup
  whois: whois

apikeys:
  nasa: ""
  shodan: ""
  opensky: ""

# Signed-off-by: ronikoz
